"""Export model + per-feature stats + archetypes for the Vercel web playground.

Reads:
  data/models/xgb_transfer_fee.pkl     (pickled XGBRegressor, sklearn wrapper)
  data/models/selected_features.json   (feature order + medians)

Writes:
  web/api/model/model.json             (xgboost native format, ~640 KB)
  web/api/model/feature_order.json     (features + medians + feature_set_hash)
  web/api/model/feature_stats.json     (per-feature P5, P95, SD + groups, for the API)
  web/public/model-info.json           (mirror of the above for the frontend, CDN-served)
  web/public/archetypes.json           (six fake-player presets)

Per-feature P5/P95/SD are hand-picked from Premier League norms (the training
feature dataframe isn't persisted — it's regenerated by train.py from a multi-step
join). Hand-picked ranges are more honest than synthetic stats from a schema
that doesn't match the model. SDs are used for the +1 SD perturbation in the
counterfactual feature; P5/P95 set slider min/max.

feature_set_hash = sha256(model-info.json bytes + model.json bytes)[:8] — any
change to features, stats, OR model weights produces a new hash. Frontend stamps
it on every saved build; mismatch triggers read-only mode in /saved.
"""
from __future__ import annotations

import hashlib
import json
import pickle
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import config  # noqa: E402
from scripts.predict import make_fake_players  # noqa: E402

MODEL_PKL = config.MODELS_DIR / "xgb_transfer_fee.pkl"
FEATS_JSON = config.MODELS_DIR / "selected_features.json"

# Hand-picked Premier League norms. P5/P95 set slider ranges; SD drives the
# +1 SD counterfactual perturbation. These are subject-matter estimates, not
# computed statistics — the training feature dataframe isn't persisted.
FEATURE_NORMS: dict[str, dict[str, float]] = {
    "MP_Playing":          {"p5": 5.0,   "p95": 38.0,  "sd": 9.0},
    "Starts_Playing":      {"p5": 0.0,   "p95": 36.0,  "sd": 11.0},
    "Mins_Per_90_Playing": {"p5": 1.0,   "p95": 35.0,  "sd": 10.0},
    "Gls":                 {"p5": 0.0,   "p95": 18.0,  "sd": 4.5},
    "Ast":                 {"p5": 0.0,   "p95": 9.0,   "sd": 2.5},
    "PK":                  {"p5": 0.0,   "p95": 5.0,   "sd": 1.2},
    "PKatt":               {"p5": 0.0,   "p95": 6.0,   "sd": 1.4},
    "CrdY":                {"p5": 0.0,   "p95": 11.0,  "sd": 2.8},
    "CrdR":                {"p5": 0.0,   "p95": 1.0,   "sd": 0.4},
    "Gls_Per":             {"p5": 0.0,   "p95": 0.65,  "sd": 0.18},
    "G+A_Per":             {"p5": 0.0,   "p95": 0.95,  "sd": 0.25},
    "G_minus_PK_Per":      {"p5": 0.0,   "p95": 0.55,  "sd": 0.16},
    "xG_Expected":         {"p5": 0.1,   "p95": 16.0,  "sd": 4.0},
    "npxG_Expected":       {"p5": 0.1,   "p95": 14.0,  "sd": 3.5},
    "xAG_Expected":        {"p5": 0.1,   "p95": 8.5,   "sd": 2.2},
}

WEB_API_MODEL = ROOT / "web" / "api" / "model"
WEB_PUBLIC = ROOT / "web" / "public"
WEB_API_MODEL.mkdir(parents=True, exist_ok=True)
WEB_PUBLIC.mkdir(parents=True, exist_ok=True)

# Correlated-feature groups for the compare-view deciding-group math.
# Locked in plan-eng-review tension T3: single-stat swap is mathematically
# broken on collinear features (xG/npxG/Gls all measure "this player scores").
# Compare swaps groups (all members at once) so input vectors stay in-distribution.
FEATURE_GROUPS = {
    "finishing_volume": ["Gls", "xG_Expected", "npxG_Expected", "Gls_Per", "G_minus_PK_Per"],
    "creation": ["Ast", "xAG_Expected", "G+A_Per"],
    "availability": ["MP_Playing", "Starts_Playing", "Mins_Per_90_Playing"],
    "discipline": ["CrdY", "CrdR"],
    "set_pieces": ["PK", "PKatt"],
}


def _compute_feature_stats(features: list[str]) -> dict[str, dict[str, float]]:
    """For each model feature, return hand-picked PL-norm P5/P95/SD."""
    missing = [f for f in features if f not in FEATURE_NORMS]
    if missing:
        raise SystemExit(f"FEATURE_NORMS missing entries for: {missing}")
    return {f: dict(FEATURE_NORMS[f]) for f in features}


def _archetype_payload(features: list[str], medians: dict[str, float]) -> list[dict]:
    """Project the 6 archetypes from scripts/predict.py onto the model's feature
    set, filling missing keys with the training-set median.
    """
    out: list[dict] = []
    for fake in make_fake_players():
        full = {feat: float(fake["stats"].get(feat, medians[feat])) for feat in features}
        out.append({
            "name": fake["name"],
            "position": fake["position"],
            "age": fake["age"],
            "features": full,
        })
    return out


def _feature_set_hash(model_info_bytes: bytes, model_json_bytes: bytes) -> str:
    h = hashlib.sha256()
    h.update(model_info_bytes)
    h.update(model_json_bytes)
    return h.hexdigest()[:8]


def main() -> None:
    if not MODEL_PKL.exists():
        raise SystemExit(f"missing {MODEL_PKL} — run scripts/train.py first")
    if not FEATS_JSON.exists():
        raise SystemExit(f"missing {FEATS_JSON} — run scripts/train.py first")

    with open(MODEL_PKL, "rb") as f:
        sk_model = pickle.load(f)

    out_model = WEB_API_MODEL / "model.json"
    booster = sk_model.get_booster()
    booster.save_model(str(out_model))
    model_json_bytes = out_model.read_bytes()

    feats = json.loads(FEATS_JSON.read_text())
    features: list[str] = feats["features"]
    medians: dict[str, float] = {k: float(v) for k, v in feats["medians"].items()}

    feature_stats = _compute_feature_stats(features)
    archetypes = _archetype_payload(features, medians)

    # Validate feature groups: every group member must be a model feature.
    for group, members in FEATURE_GROUPS.items():
        unknown = [m for m in members if m not in features]
        if unknown:
            raise SystemExit(f"feature group {group!r} references unknown features: {unknown}")

    # Build the public model-info payload first (frontend), then hash it together
    # with model.json bytes to lock the schemaVersion.
    model_info_payload = {
        "features": features,
        "medians": medians,
        "feature_stats": feature_stats,
        "feature_groups": FEATURE_GROUPS,
        # feature_set_hash gets injected after we hash this payload + model bytes
    }
    public_info = WEB_PUBLIC / "model-info.json"
    public_archetypes = WEB_PUBLIC / "archetypes.json"

    # Hash without the hash field, then inject it.
    base_bytes = json.dumps(model_info_payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    feature_set_hash = _feature_set_hash(base_bytes, model_json_bytes)
    model_info_payload["feature_set_hash"] = feature_set_hash

    public_info.write_text(json.dumps(model_info_payload, indent=2))
    public_archetypes.write_text(json.dumps(archetypes, indent=2))

    # Python-side sidecar: same data, different destination, same hash.
    out_features = WEB_API_MODEL / "feature_order.json"
    out_features.write_text(json.dumps({
        "features": features,
        "medians": medians,
        "feature_set_hash": feature_set_hash,
    }, indent=2))

    out_stats = WEB_API_MODEL / "feature_stats.json"
    out_stats.write_text(json.dumps({
        "feature_stats": feature_stats,
        "feature_groups": FEATURE_GROUPS,
        "feature_set_hash": feature_set_hash,
    }, indent=2))

    print(f"wrote {out_model} ({out_model.stat().st_size} bytes)")
    print(f"wrote {out_features} ({len(features)} features)")
    print(f"wrote {out_stats} ({len(feature_stats)} feature stats)")
    print(f"wrote {public_info} ({len(features)} features, {len(FEATURE_GROUPS)} groups)")
    print(f"wrote {public_archetypes} ({len(archetypes)} archetypes)")
    print(f"feature_set_hash = {feature_set_hash}")


if __name__ == "__main__":
    main()
