"""Export model + per-feature stats + archetypes for the Vercel web playground.

Reads:
  data/models/xgb_transfer_fee.pkl     (pickled XGBRegressor, sklearn wrapper)
  data/models/selected_features.json   (feature order + medians)

Writes:
  web/api/model/model.json             (xgboost native format, ~640 KB)
  web/api/model/feature_order.json     (features + medians + feature_set_hash)
  web/api/model/feature_stats.json     (per-feature P5, P95, SD + groups, for the API)
  web/public/model-info.json           (mirror of the above for the frontend, CDN-served)
  web/public/archetypes.json           (six fake-player presets)

Per-feature P5/P95/SD are hand-picked from Premier League norms (the training
feature dataframe isn't persisted — it's regenerated by train.py from a multi-step
join). Hand-picked ranges are more honest than synthetic stats from a schema
that doesn't match the model. SDs are used for the +1 SD perturbation in the
counterfactual feature; P5/P95 set slider min/max.

feature_set_hash = sha256(model-info.json bytes + model.json bytes)[:8] — any
change to features, stats, OR model weights produces a new hash. Frontend stamps
it on every saved build; mismatch triggers read-only mode in /saved.
"""
from __future__ import annotations

import hashlib
import json
import pickle
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import config  # noqa: E402
from scripts.predict import make_fake_players  # noqa: E402

MODEL_PKL = config.MODELS_DIR / "xgb_transfer_fee.pkl"
FEATS_JSON = config.MODELS_DIR / "selected_features.json"

# Feature norms are now derived from training-set medians + stds persisted
# in selected_features.json (see _compute_feature_stats). Hand-picked norms
# are gone — the model schema is too wide (23+ features across 6 FBref tables
# plus engineered fields) and the persisted training stats are authoritative.

WEB_API_MODEL = ROOT / "web" / "api" / "model"
WEB_PUBLIC = ROOT / "web" / "public"
WEB_API_MODEL.mkdir(parents=True, exist_ok=True)
WEB_PUBLIC.mkdir(parents=True, exist_ok=True)

# Correlated-feature groups for the compare-view "decide-as-a-group" math.
# Locked in plan-eng-review tension T3: single-stat swap is broken on collinear
# features. With the enriched feature set we group by FBref table suffix
# (_shoot/_pass/_poss/_def/_misc) plus engineered families (profile, valuation,
# position). Group membership is computed from the actual feature list so
# adding/removing features doesn't require touching this map.

def _group_for(feature: str) -> str:
    if feature in {"prior_market_value_eur"}:
        return "valuation"
    if feature.startswith("pos_"):
        return "position"
    if feature in {"age_years", "age_sq", "peak_distance",
                   "contract_years_remaining", "tenure_at_selling_club_years"}:
        return "profile"
    if feature.endswith("_shoot"):
        return "finishing"
    if feature.endswith("_pass"):
        return "passing"
    if feature.endswith("_poss"):
        return "possession"
    if feature.endswith("_def"):
        return "defending"
    if feature.endswith("_misc"):
        return "misc"
    # Standard-table fallbacks
    if feature in {"MP_Playing", "Starts_Playing", "Mins_Per_90_Playing", "Min_Playing"}:
        return "availability"
    if feature in {"CrdY", "CrdR"}:
        return "discipline"
    if feature in {"Gls", "Gls_Per", "G_minus_PK", "G_minus_PK_Per", "G+A_Per", "G+A_minus_PK_Per"}:
        return "finishing"
    if feature in {"Ast", "Ast_Per", "xAG_Expected", "xAG_Per"}:
        return "creation"
    if feature in {"PK", "PKatt"}:
        return "set_pieces"
    return "other"


def _build_feature_groups(features: list[str]) -> dict[str, list[str]]:
    groups: dict[str, list[str]] = {}
    for f in features:
        groups.setdefault(_group_for(f), []).append(f)
    return groups


def _compute_feature_stats(
    features: list[str],
    medians: dict[str, float],
    stds: dict[str, float],
) -> dict[str, dict[str, float]]:
    """Derive P5/P95/SD per feature from training-time medians + stds.

    P5 ≈ median - 2*sd  (clamped at 0 for nonnegative-by-construction stats)
    P95 ≈ median + 2*sd
    SD  = persisted training std
    """
    nonneg_prefixes = ("MP_", "Min_", "Mins_", "Starts_", "Gls", "Ast", "PK", "Crd",
                       "xG_", "npxG_", "xA", "Sh_", "SoT_", "Tkl", "Cmp_", "Att_",
                       "Won_", "Lost_", "Press_", "Touch", "Carry", "Carries", "Prog",
                       "Rec_", "Final_", "Recov", "Int_", "Clr_", "Blocks_",
                       "Dist_", "TotDist", "PrgDist", "Live_", "Targ_",
                       "prior_market_value_eur", "age_years", "age_sq",
                       "contract_years_remaining", "tenure_at_selling_club_years",
                       "peak_distance", "seasons_in_big5_prior", "min_prior",
                       "xg_per90", "xag_per90", "from_", "pos_", "foot_",
                       "window_winter", "nat_is_")
    out = {}
    for f in features:
        sd = float(stds.get(f, 1.0))
        med = float(medians.get(f, 0.0))
        p5 = med - 2 * sd
        p95 = med + 2 * sd
        if f.startswith(nonneg_prefixes):
            p5 = max(0.0, p5)
        out[f] = {"p5": p5, "p95": p95, "sd": sd}
    return out


def _archetype_payload(
    features: list[str],
    medians: dict[str, float],
    inverse_rename: dict[str, str],
) -> list[dict]:
    """Project the 6 archetypes from scripts/predict.py onto the model's feature
    set, filling missing keys with the training-set median. Fake stats are
    keyed by ORIGINAL feature names; the model expects xgb-safe names.
    """
    out: list[dict] = []
    for fake in make_fake_players():
        full = {}
        for feat in features:
            orig = inverse_rename.get(feat, feat)
            if orig in fake["stats"]:
                full[feat] = float(fake["stats"][orig])
            else:
                full[feat] = float(medians.get(feat, 0.0))
        out.append({
            "name": fake["name"],
            "position": fake["position"],
            "age": fake["age"],
            "features": full,
        })
    return out


def _feature_set_hash(model_info_bytes: bytes, model_json_bytes: bytes) -> str:
    h = hashlib.sha256()
    h.update(model_info_bytes)
    h.update(model_json_bytes)
    return h.hexdigest()[:8]


def main() -> None:
    if not MODEL_PKL.exists():
        raise SystemExit(f"missing {MODEL_PKL} — run scripts/train.py first")
    if not FEATS_JSON.exists():
        raise SystemExit(f"missing {FEATS_JSON} — run scripts/train.py first")

    with open(MODEL_PKL, "rb") as f:
        sk_model = pickle.load(f)

    out_model = WEB_API_MODEL / "model.json"
    booster = sk_model.get_booster()
    booster.save_model(str(out_model))
    model_json_bytes = out_model.read_bytes()

    feats = json.loads(FEATS_JSON.read_text())
    features: list[str] = feats["features"]
    # Medians are persisted keyed by ORIGINAL feature names; stds by xgb-safe.
    # Build aligned dicts keyed by the xgb-safe names used in `features`.
    rename_map: dict[str, str] = feats.get("rename_map", {})
    inverse_rename = {v: k for k, v in rename_map.items()}
    medians_raw: dict[str, float] = {k: float(v) for k, v in feats["medians"].items()}
    stds_raw: dict[str, float] = {k: float(v) for k, v in feats.get("stds", {}).items()}
    medians: dict[str, float] = {f: float(medians_raw.get(inverse_rename.get(f, f), 0.0)) for f in features}
    stds: dict[str, float] = {f: float(stds_raw.get(f, 1.0)) for f in features}

    feature_groups = _build_feature_groups(features)
    feature_stats = _compute_feature_stats(features, medians, stds)
    archetypes = _archetype_payload(features, medians, inverse_rename)

    # Build the public model-info payload first (frontend), then hash it together
    # with model.json bytes to lock the schemaVersion.
    model_info_payload = {
        "features": features,
        "medians": medians,
        "feature_stats": feature_stats,
        "feature_groups": feature_groups,
        # feature_set_hash gets injected after we hash this payload + model bytes
    }
    public_info = WEB_PUBLIC / "model-info.json"
    public_archetypes = WEB_PUBLIC / "archetypes.json"

    # Hash without the hash field, then inject it.
    base_bytes = json.dumps(model_info_payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    feature_set_hash = _feature_set_hash(base_bytes, model_json_bytes)
    model_info_payload["feature_set_hash"] = feature_set_hash

    public_info.write_text(json.dumps(model_info_payload, indent=2))
    public_archetypes.write_text(json.dumps(archetypes, indent=2))

    # Python-side sidecar: same data, different destination, same hash.
    out_features = WEB_API_MODEL / "feature_order.json"
    out_features.write_text(json.dumps({
        "features": features,
        "medians": medians,
        "feature_set_hash": feature_set_hash,
    }, indent=2))

    out_stats = WEB_API_MODEL / "feature_stats.json"
    out_stats.write_text(json.dumps({
        "feature_stats": feature_stats,
        "feature_groups": feature_groups,
        "feature_set_hash": feature_set_hash,
    }, indent=2))

    print(f"wrote {out_model} ({out_model.stat().st_size} bytes)")
    print(f"wrote {out_features} ({len(features)} features)")
    print(f"wrote {out_stats} ({len(feature_stats)} feature stats)")
    print(f"wrote {public_info} ({len(features)} features, {len(feature_groups)} groups)")
    print(f"wrote {public_archetypes} ({len(archetypes)} archetypes)")
    print(f"feature_set_hash = {feature_set_hash}")


if __name__ == "__main__":
    main()
